// AUTO-GENERATED BY @sidebase/nuxt-auth
import { RouteOptions } from '/Users/daigoro/Dev/daigoroCode/ImaTrip/ImaTripAdmin/node_modules/@sidebase/nuxt-auth/dist/runtime/types.ts'
declare module 'nitropack' {
  interface NitroRouteRules {
    auth?: RouteOptions
  }
  interface NitroRouteConfig {
    auth?: RouteOptions
  }
}
